name: GitHub CI
on:
  pull_request:
  workflow_dispatch:
  push:
    tags:
      - "*"
    branches:
      - main
      - release/*

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  style:
    name: Code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Run code style
        run: make style

  docs:
    name: Documentation
    runs-on: [self-hosted, pyfluent]
    env:
      DOCUMENTATION_CNAME: examples.fluent.docs.pyansys.com

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Generate the documentation
        run: make build-doc

      - name: Upload HTML Documentation
        uses: actions/upload-artifact@v4
        with:
          name: HTML-Documentation
          path: doc/_build/html
          retention-days: 7
