name: Nightly Examples Run

on:
  schedule:  # UTC at 0400
    - cron:  '0 4 * * *'
  workflow_dispatch:

env:
  DOCUMENTATION_CNAME: 'examples.fluent.docs.pyansys.com'
  DOC_DEPLOYMENT_IMAGE_TAG: v23.1.0

jobs:
  nightly_docs_build:
    runs-on: [self-hosted, pyfluent]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.REPO_DOWNLOAD_PAT }}

      - name: Pull Fluent docker image
        run: make docker-pull
        env:
          FLUENT_IMAGE_TAG: ${{ env.DOC_DEPLOYMENT_IMAGE_TAG }}

      - name: Generate the documentation
        run: make build-doc
        env:
          ANSYSLMD_LICENSE_FILE: ${{ format('1055@{0}', secrets.LICENSE_SERVER) }}
          PYFLUENT_START_INSTANCE: 0
          PYFLUENT_LAUNCH_CONTAINER: 1
          FLUENT_IMAGE_TAG: ${{ env.DOC_DEPLOYMENT_IMAGE_TAG }}
          RUN_EXAMPLES: 1

      - name: Upload HTML Documentation
        uses: actions/upload-artifact@v3
        with:
          name: HTML-Documentation-with-examples-run-${{ env.DOC_DEPLOYMENT_IMAGE_TAG }}
          path: doc/_build/html
          retention-days: 7
